version: "3"

services:

  timescaledb:
    image: tdmproject/tdmq-db:dev-373
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=tdmqtest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foobar
      - START_DB=true
      - POSTGRES_RUN_MIGRATIONS=true
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=postgres" ]
      interval: "15s"
      retries: 5

  web:
    # Remember that this service is using its default configuration
    # to access the database, so the settings must match the environment
    # configuration set for timescaledb above.
    image: tdmproject/tdmq:dev-373
    depends_on:
      - "timescaledb"
    ports:
      - "8000:8000"
    user: 1000:1000
    env_file: &env_file
      - settings.conf
    environment:
      - "CREATE_DB=false"
      - "DEV=true"
    healthcheck:
      test: [ "CMD", "/usr/bin/curl", "http://web:8000/api/v0.0/entity_types" ]
      interval: "30s"
      timeout: "5s"
      retries: "3"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    env_file: *env_file
    environment:
      - MINIO_BROWSER=off
      - MINIO_HTTP_TRACE=/dev/stderr
    entrypoint: [ "/bin/sh", "-c",
                  "mkdir -p /data/$${STORAGE_BUCKET} && exec /usr/bin/docker-entrypoint.sh minio server /data" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  tdmq-jupyter:
    image: tdmproject/tdmqj:dev-373
    ports:
      - "8888:8888"
    volumes:
      - "../notebook.ipynb:/home/jovyan/notebook.ipynb"
    env_file: *env_file
    environment:
      - NB_UID=1000
      - NB_GID=1000
      - JUPYTER_ENABLE_LAB=yes

